version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  app:
    build: .
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - DB_HOST_CONNECTION=mongo
    restart: always
    ports:
      - 8000:8000