version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  app:
    build: .
    depends_on:
      - mongo
    restart: always
    ports:
      - 8000:8000